name: Daily Repository Update

on:
  schedule:
    # Runs at 05:30 UTC every day
    - cron: "30 5 * * *"
  workflow_dispatch: # Allow manual triggers for testing

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Step for 23f2005282@ds.study.iitm.ac.in
        run: |
          echo "Running daily update for 23f2005282@ds.study.iitm.ac.in"
          date > daily-update.txt
          echo "Last updated: $(date)" >> daily-update.txt

      - name: Create daily commit
        run: |
          git config --local user.email "23f2005282@ds.study.iitm.ac.in"
          git config --local user.name "DevSync Automation"
          git add daily-update.txt
          git commit -m "Daily update: $(date +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push